import { BaseWindow, BaseRectangle,GlobalBasicSettings,ContentType } from "../config/global.slint";
import { Button, HorizontalBox } from "std-widgets.slint";
import { titlemenu, BaseSidebar, BaseResizablePane } from "BaseCompont.slint";

export component Setting inherits BaseWindow {
    in-out property <bool> fullscreen:false;
    private property <ContentType> current-content: ContentType.None;
    preferred-width: 600px;
    no-frame: true;
    title: "Setting";
    BaseRectangle {
        VerticalLayout {
            titlemenu{
                title-icons:GlobalBasicSettings.theme-type.icon-setting;
                closewindow => {
                    root.closewindow()
                }
                maximize => {
                    root.maximize_window()
                }
                minimize => {
                    root.minimize_window()
                }
            }
            HorizontalLayout {
                spacing: 0px;
                sidder := BaseSidebar{
                    background: GlobalBasicSettings.theme-type.sidebar-bg;
                }
                Rectangle {
                    BaseResizablePane {
                        Text {
                            text: @tr("内容区域");
                        }
                    }
                }

            }
        }
    }
}