import { theme-dark,theme-ligth,GlobalTheme } from "./theme.slint";
export struct LogEntry {
    timestamp: string,
    level: string,
    message: string,
}



// 全局基础设置
export global GlobalBasicSettings {
    callback closewindow();
    callback openwindow();
    callback maximize_window() -> bool;
    callback minimize_window();
    callback handle_event();
    callback ligth_dark();
    in-out property <[LogEntry]> logs;
    callback get_logs() -> [LogEntry];
    // 窗口基础设置
    out property <string> title:"Gtrat2";
    out property <length> default-width: 1000px;
    out property <length> default-height : 870px;
    out property <color> background:transparent;
    out property <length> border_radius:10px;
    out property <color> rectangle_bg:#27282b;
    in-out property <GlobalTheme> theme-type:theme-ligth.default_theme;
    out property <image> icon-image:theme-type.icon-logo;
    // 字体设置
    out property <string> default_font_family:"Cascadia Code";
    out property <length> default_font_size:13px;


    // 组件属性
    in-out property <string> active_tab: "Event Log"; 
    in-out property <[string]> visible_tabs:["Event Log"];
    callback remove_tab(string);
    callback add_tab(string);
}


export enum ContentType {
    None,
    Create,
    Home
}




export component BaseWindow inherits Window {
    in-out property <image> title-icons:GlobalBasicSettings.icon-image;
    icon: title-icons;
    title: GlobalBasicSettings.title;
    preferred-width: GlobalBasicSettings.default-width;
    preferred-height: GlobalBasicSettings.default-height;
    background: GlobalBasicSettings.background;
    default-font-family: GlobalBasicSettings.default-font-family;
    default-font-size: GlobalBasicSettings.default-font-size;
    // 定义可重写的回调
    callback closewindow();
    callback openwindow();
    callback maximize_window() -> bool;
    callback minimize_window();
    
    // 默认实现
    minimize_window => {GlobalBasicSettings.minimize_window()}
    maximize_window => {  GlobalBasicSettings.maximize_window() }
    closewindow => { GlobalBasicSettings.closewindow(); }
    openwindow => { GlobalBasicSettings.openwindow(); }
    

}

export component BaseRectangle inherits Rectangle {
    background: GlobalBasicSettings.rectangle_bg;
    border-radius: GlobalBasicSettings.border_radius;

}